### ISSUE TITLE
Grakn-client 1.7.2 needs to be compatible with protobuf 3.8.0 and grpcio 1.24.3 or newer

### ISSUE THREAD

**Issue by pw-ai** [graknlabs/client-python#101]
## Description
When installing grakn-client, the following message shows up:

ERROR: tensorflow 2.1.0 has requirement protobuf>=3.8.0, but you'll have protobuf 3.6.1 which is incompatible.
ERROR: tensorflow-hub 0.8.0 has requirement protobuf>=3.8.0, but you'll have protobuf 3.6.1 which is incompatible.
ERROR: tensorboard 2.1.1 has requirement grpcio>=1.24.3, but you'll have grpcio 1.24.1 which is incompatible.
ERROR: ray 0.8.5 has requirement protobuf>=3.8.0, but you'll have protobuf 3.6.1 which is incompatible.

## Environment

1. OS (where Grakn server runs): Ubuntu 18.04
2. Grakn version (and platform): 1.7
3. Grakn client-python version: 1.7.2
4. Python version: 3.7
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. pip install -U grakn-client==1.7.2
## Expected Output

no error messages indicating incompatibility

## Actual Output

ERROR: tensorflow 2.1.0 has requirement protobuf>=3.8.0, but you'll have protobuf 3.6.1 which is incompatible.
ERROR: tensorflow-hub 0.8.0 has requirement protobuf>=3.8.0, but you'll have protobuf 3.6.1 which is incompatible.
ERROR: tensorboard 2.1.1 has requirement grpcio>=1.24.3, but you'll have grpcio 1.24.1 which is incompatible.
ERROR: ray 0.8.5 has requirement protobuf>=3.8.0, but you'll have protobuf 3.6.1 which is incompatible.

**Comment by pandemosth** [comment]
I'm having a similar issue - a conflict with Streamlit which requires protobuf 3.13.0.
Is there an eta for the 2.0 milestone or a fix for this?
Thanks

**Comment by alexjpwalker** [comment]
We have just released https://github.com/graknlabs/client-python/releases/tag/2.0.0-alpha which upgrades Grakn to 2.0 and upgrades `grpcio` to 1.33.2, which should resolve this issue.

**Comment by alexjpwalker** [comment]
We have just released `grakn-client==2.0.0`, which additionally upgrades `grpcio` to 1.36.1, `protobuf` to 3.15.5, so this issue can definitely be considered resolved.
