### ISSUE TITLE
Session pulse producing too many threads

### ISSUE THREAD

**Issue by vmax** [graknlabs/client-python#158]
## Description

Currently, each session pulse is sent in a separate thread; a few minutes of keeping session open shows the thread number grow:

```
In [60]: threading.enumerate()
Out[60]: 
[<_MainThread(MainThread, started 140324098783040)>,
 <HistorySavingThread(IPythonHistorySavingThread, started 140324065166912)>,
 <Thread(Thread-293, started daemon 140323535701568)>,
 <Thread(Thread-294, started daemon 140323552486976)>]
```

Refactor proposals:
* instead of creating new threads over and over, use [`concurrent.futures.ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) which creates new threads on demand (but keeps some alive and doesn't create excess of them)
* Name it accordingly, including the session name such that it's easy to differentiate them:

```
In [1]: from concurrent.futures import ThreadPoolExecutor
In [2]: ex = ThreadPoolExecutor(thread_name_prefix='session_pulse_6688ccd6278d4b959a499f4cb2e49ffb')
In [3]: threading.enumerate()
Out[3]: 
[<_MainThread(MainThread, started 139758585063232)>,
 <HistorySavingThread(IPythonHistorySavingThread, started 139758551447104)>,
 <Thread(session_pulse_6688ccd6278d4b959a499f4cb2e49ffb_0, started daemon 139758437135936)>]
```

**Comment by haikalpribadi** [comment]
Isn't this a critical bug, @alexjpwalker ? This would cause a thread-leak on the client system, right?

**Comment by alexjpwalker** [comment]
> Isn't this a critical bug, @alexjpwalker ? This would cause a thread-leak on the client system, right?

I don't know how severe it is. I suppose we could test creating 10,000 sessions and see if the system grinds to a halt?

**Comment by haikalpribadi** [comment]
Okay then I'm keeping this in the current milestone then, with priority "high".

**Comment by vmax** [comment]
@alexjpwalker @haikalpribadi elaborating: this is not a **very** critical issue: old threads are getting garbage collected after they finished running - it's just that new ones are created with a higher and higher index. By using a thread pool we would avoid a bit of overhead and make a code _a bit_ cleaner.
