### ISSUE TITLE
read_transaction.concepts().get_thing_type() raises AttributeError: 'ConceptManager' object has no attribute 'get_thing_type'

### ISSUE THREAD

**Issue by JonThom** [graknlabs/client-python#172]
## Description

When calling `read_transaction.concepts().get_thing_type("relation")` I get 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'ConceptManager' object has no attribute 'get_thing_type'

## Environment

1. OS (where Grakn server runs): Mac OS 10.14.6
2. Grakn version (and platform): Grakn Core 2.0.0-alpha-3
3. Grakn client-python version: client-python 2.0.0a5
4. Python version: 3.9

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open a python terminal
2. `from grakn.client import *`
3. `client = GraknClient("127.0.0.1:1729")`
4. `session = client.session(<myschema>, SessionType.SCHEMA)`
5. `tx = session.transaction(TransactionType.READ)`
6. `tx.concepts().get_thing_type("relation")`

## Expected Output

a type object

## Actual Output

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'ConceptManager' object has no attribute 'get_thing_type'

**Comment by VladGan** [comment]
@JonThom thanks for submitting the issue, we fixed it in https://github.com/graknlabs/client-python/pull/174
