### ISSUE TITLE
AttributeError: type object 'GraknClient' has no attribute 'core'

### ISSUE THREAD

**Issue by JonThom** [graknlabs/client-python#184]
## Description

calling `GraknClient.core("localhost:1729")` fails

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn core 2.0
3. Grakn client-python version: client-python 2.0.0a6
4. Python version: 3.9

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. install grakn, the grakn python client
2. open python
3. `from grakn.client import *`
4. `client = GraknClient.core("localhost:1729")`

## Expected Output

None 

## Actual Output

>  AttributeError: type object 'GraknClient' has no attribute 'core'
 
## Additional information

`help(GraknClient)` shows that the 'core' method is indeed missing

**Comment by alexjpwalker** [comment]
Are you sure you're using `grakn-client==2.0.0a6`, @JonThom ?

The attribute `core` definitely exists - see the relevant [source code:](https://github.com/graknlabs/client-python/blob/55942495b5b1bd8f77c42c5d85352ca2944e64d5/grakn/client.py#L45)

```py
@staticmethod
def core(address=DEFAULT_ADDRESS) -> "GraknClient":
    return _ClientRPC(address)
```

**Comment by JonThom** [comment]
@alexjpwalker I must have been calling the client within the wrong environment. Apologies for the false alarm!

**Comment by thistleknot** [comment]
same using grak-client 2.0.1
>>> dir(GraknClient)
['__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', 'close', 'databases', 'is_cluster', 'is_open', 'session']

**Comment by benjaminasmall** [comment]
Hi, @thistleknot : Do you still have these problems with the new version?
