### ISSUE TITLE
client.databases().delete(<database>) raises AttributeError: '_DatabaseManagerRPC' object has no attribute 'delete'

### ISSUE THREAD

**Issue by JonThom** [graknlabs/client-python#195]
## Description

calling `client.databases().delete(<database>)` raises AttributeError: 
> '_DatabaseManagerRPC' object has no attribute 'delete'

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 2.0.0-alpha-8
3. Grakn client-python version: client-python 2.0.0-alpha-8
4. Python version: 3.8.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Open a Python REPL, then
1. `from grakn.client import *`
2. `client = GraknClient.core("localhost:1729")`
3. `client.databases().create(“test”)`
4. `client.databases().delete("test”)`

## Expected Output

silent deletion of "test" database

## Actual Output

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: '_DatabaseManagerRPC' object has no attribute 'delete'

**Comment by vmax** [comment]
@JonThom `delete` method has indeed been deleted from database object, quoting the [release notes](https://github.com/graknlabs/client-python/releases/tag/2.0.0-alpha-8) of `alpha8`:

>Additionally, client.databases().delete() has been deleted, and superseded by the new syntax: client.databases().get(name).delete()

Thanks for the reporting! We shall update it [in the docs](https://dev.docs.grakn.ai/) too.
