### ISSUE TITLE
test-cluster-failover is flaky

### ISSUE THREAD

**Issue by lolski** [graknlabs/client-python#197]
## Description

https://grabl.io/flyingsilverfin/client-python/989e727c8ef6c8e0ac1de8247b868d21a2515157/build/2/correctness/1/test-cluster-failover/1

## Environment

1. OS (where Grakn server runs): Ubuntu 20
2. Grakn version (and platform): the artifact that's included in the repository
3. Grakn client-python version: `flyingsilverfin/client-python@989e727c8ef6c8e0ac1de8247b868d21a2515157`

**Comment by alexjpwalker** [comment]
fixed in https://github.com/graknlabs/client-python/pull/198
