### ISSUE TITLE
python client data read issue

### ISSUE THREAD

**Issue by tahsintahsin** [graknlabs/client-python#206]
Hello, 

In my local machine (python 3.8.2 on macos big sur ), I am experimenting with grakn server 2.0.0-alpha-8 with python client grakn-client==2.0.0a10.

Using the Grakn console, I am able to do create-delete databases, load schemas, insert data, and read it, 
However, in python client I am having serious issues with reading data from the database.
I have a very simple db called 'grakn' where i inserted 6 lion entities (it was an example in the documentation)

With the code below I successfully get a map object,

```

from grakn.client import GraknClient, SessionType, TransactionType

q='match $x isa lion; get $x;'

with GraknClient.core("localhost:1729") as client:

    with client.session("grakn", SessionType.DATA) as session:

        with session.transaction(TransactionType.READ) as tx:

            answer_iterator = tx.query().match(q)

            print(answer_iterator)

```

When I want to access fields of it either via iteration as  "for x in aswer_iterator etc" or via trying to convert it to a list "list(answer_iterator)" as shown in the examples in the documentation of the client, i get the following error:
GraknClientException: The encoding 0 was not recognised.

Any idea how I can troubleshoot the issue? 
Thanks

**Comment by haikalpribadi** [comment]
@alexjpwalker can you take a look into the issue above?

**Comment by alexjpwalker** [comment]
@tahsintahsin This error is most likely caused by a version mismatch. Can you try upgrading your Grakn Core Server to 2.0.0-alpha-9?

**Comment by tahsintahsin** [comment]
that worked (grakn-client==2.0.0a10 and grakn core server 2.0.0-alpha-9), thank you so much !

**Comment by alexjpwalker** [comment]
Okay, good stuff 👍
