### ISSUE TITLE
Client Python: file structure naming is unclear

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/client-python#40]
To use the class `Concept` in Python it is necessary to import as follows:
```
from grakn.service.Session.Concept import Concept

is_a_concept = isInstance(my_concept, Concept.Concept)
```
From a user perspective this is confusing since there is a package called `Concept`, containing a file called `Concept`, containing a class called `Concept`.

I believe ideal best practice would be to use lower case names for packages, and that they should be named according to a summary of their content. I don't know whether this would conflict with our naming across our other drivers but something should be done to limit the confusion here if possible.

**Comment by alexjpwalker** [comment]
The new naming structure in 2.0 is as follows:

- Packages are all lowercase
- Classes are all PascalCase

The result is that, for example, `Type` is loaded as: `from grakn.concept.type.type import Type`. It's not ideal - there is still some duplication in the path - but it is now pretty clear what is a package and what is a class.

Moreover, for anything _other_ than `Type` itself, the path is fully coherent: `from grakn.concept.type.attribute_type import BooleanAttributeType`.
