### ISSUE TITLE
Provide a method for checking if a transaction is open

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/client-python#70]
## Problem to Solve
At the moment, there is no straight forward way of checking whether a transaction is still open.

## Current Workaround
Run some basic query and see if a `Transaction is already closed` error is returned. 

## Proposed Solution
Expose `is_open` on `transaction`

**Comment by flyingsilverfin** [comment]
This exists on transaction: `transaction.is_open()` (after PR #72 )
