### ISSUE TITLE
Provide __str__ implementations for Client Objects

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/client-python#74]
## Problem to Solve
The client would be more user friendly and faster to interactively work with if all of the classes defined provide a nice `__str__()` representation. For instance, a `Concept` being printed would show its base type and ID (local information) rather than a memory address, Answers could print the concept maps/list/sets and explanations in string format, transaction could show the type, session could show the keyspace etc. 

## Current Workaround
Manually print out by calling specific methods to retrieve desired information

## Proposed Solution
* Implement `__str__()` to print object contents better

**Comment by alexjpwalker** [comment]
This was implemented as one of the enhancements for Client Python 2.0 in https://github.com/graknlabs/client-python/pull/133 .
