### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/client-python#76]
## Problem to Solve
Once Python 2 support is removed, we should implement proper type annotations/hinting throughout the client.

## Current Workaround
Incomplete usage of `__init__.__annotations__ = {...}`

## Proposed Solution
TODO figure out best solution, mypy, typing in python etc. Not sure what the current state of things is!

**Comment by alexjpwalker** [comment]
I have added some basic type annotations using the `typing` package, however there is still much work to be done. I was initially hoping to annotate every parameter and local variable, but this is not currently possible because it results in circular package imports which cause runtime errors.

**Comment by alexjpwalker** [comment]
The circular package import issue was resolved by use of

```py
if TYPE_CHECKING:
    from grakn.api.transaction import GraknTransaction
```

Type annotations are now used throughout the client.
