### ISSUE TITLE
Dependency issue in KDE Neon

### ISSUE THREAD

**Issue by dcalano** [graknlabs/client-python#90]
OS: KDE Neon 5.18.5 (Ubuntu 18.04 LTS); 5.3.0-51-generic
CPython: 3.8.2, using Pyenv 1.2.18 and Poetry 1.0.5

➜ poetry show --tree
pytest 5.4.2 pytest: simple powerful testing with Python
├── atomicwrites >=1.0
├── attrs >=17.4.0
├── colorama *
├── more-itertools >=4.0.0
├── packaging *
│   ├── pyparsing >=2.0.2
│   └── six *
├── pluggy >=0.12,<1.0
├── py >=1.5.0
└── wcwidth *

When I go to install grakn-client with "poetry add grakn-client" or "pip install grakn-client", I get the following error. This occurs with the project's Poetry virtualenv enabled and disabled.

`ERROR: Command errored out with exit status 1:
     command: /home/user/Development/Projects/Python/KnowledgeGraph/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-logm33dw/grakn-client/setup.py'"'"'; file='"'"'/tmp/pip-install-logm33dw/grakn-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-p8y0pq8l
         cwd: /tmp/pip-install-logm33dw/grakn-client/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/Development/Projects/Python/KnowledgeGraph/.venv/lib/python3.8/site-packages/setuptools/init.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/home/user/Development/Projects/Python/KnowledgeGraph/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/user/Development/Projects/Python/KnowledgeGraph/.venv/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/user/.pyenv/versions/3.8.2/lib/python3.8/ctypes/init.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

The install always fails on enum-compat. Grakn-client attempts to install enum-compat==0.0.2, even if 0.0.3 (which installs fine) is already present.

**Comment by flyingsilverfin** [comment]
@vmax I think since we're deprecating the python 2.x support, maybe we can remove some of the compatibility libs we used for the dual python 2/3 support? This issue could be rolled into that change (relaxing `enum` requirement to be a strict `==0.0.2`, and if possibel also loosening gRPC's strict `==` requirement)

**Comment by vmax** [comment]
@dcalano the traceback you shared looks similar to [this](https://stackoverflow.com/questions/27022373/) issue. Could you try the fix suggested there, which is `sudo apt-get install libffi-dev`? In the meantime, we'll work on relaxing strict dependencies

**Comment by dcalano** [comment]
Hey @vmax I had actually tried this fix before posting. I had tried adding libffi-dev but no luck, I had also tried to install all of the packages listed under MikeiLL.'s comment but no luck still on that.

**Comment by flyingsilverfin** [comment]
this should be helped with #91

**Comment by flyingsilverfin** [comment]
@dcalano please try grakn-client 1.7.2 to see if the issue is resolved :)

**Comment by dcalano** [comment]
Hi, apologies for the late reply! I am able to instal now :)

**Comment by flyingsilverfin** [comment]
cheers!
